window.languages = [
    ['zh-Hans', '简体中文', {
        'loading': '少女祈祷中……',
        'tip-1': '试试打开声音吧～',
        'tip-2': '点按此前输入的圆圈，可以重新播放声音',
        'tip-3': '推荐在夜晚使用深色主题',
        'tip-4': '可以从选项界面开启节拍器哦',
        'tip-5': '试过以字母和图形进行游戏吗？',
        'rules': 'Medle 游戏规则',
        'rule-01': '猜出旋律中的每个音符。',
        'rule-02': '玩家不必具备音乐知识，Medle 可以是纯粹的数字游戏。',
        'rule-03': '音符用 1 至 7 的数字表示。每次猜测后，将针对每个音符给出提示。',
        'rule-11': '音符“2”处于谜底中的正确位置。',
        'rule-12': '音符“3”出现在谜底中，但并不在猜测的位置上。',
        'rule-21': '若同一音符出现多次，则也会提示多次。',
        'rule-31': '一个音符“1”在正确的位置；除此之外，谜底中还有两个“1”，但都不在猜测为“1”的位置上。',
        'rule-41': '游戏中出现的其余记号只影响发出的声音，不影响游戏规则。',
        'rule-51': '除数字、颜色外的记号均不影响游戏。其含义留给有兴趣的玩家自行探索。',
        'rule-61': '一共有 5 次机会（谜底大于 9 个音符则为 6 次）。游戏愉快～',
        'daily-update': '原版网址为 medle.0-th.art 。北京时间每日零时更新谜题，记得回来呀！',
        'guide-today-1-pfx': '正在访问的是一份过往的谜题 ',
        'guide-today-1-sfx': '。',
        'guide-today-2-pfx': '希望继续游玩，还是前往今天的每日谜题 ',
        'guide-today-2-sfx': ' 呢？',
        'btn-confirm': '确认',
        'btn-share': '分享',
        'btn-shared': '已复制到剪贴板',
        'curator': '选题',
        'curator-today': '今日选题',
        'archive': '过往谜题',
        'opt-title': '选项',
        'opt-sfx': '播放声音',
        'opt-metronome': '节拍提示',
        'opt-dark': '深色主题',
        'opt-high-con': '清晰显示',
        'opt-nota': '音符记号',
        'opt-nota-num': '数字',
        'opt-nota-solf': '唱名',
        'opt-nota-alpha': '字母',
        'opt-nota-roman': '罗马',
        'opt-nota-aikin': '图形',
        'opt-lang': '界面语言',
        'opt-source': '程序源码',
        'opt-dist': '依照木兰公共许可证分发',
    }],
    ['zh-Hant', '繁體中文', {
        'loading': '少女祈禱中……',
        'tip-1': '試著打開聲音吧？',
        'tip-2': '點按此前輸入的圓圈，可以重新播放聲音',
        'tip-3': '在夜晚推薦使用深色主題',
        'tip-4': '可以從選項介面開啓節拍器哦',
        'tip-5': '試過以字母和圖形進行遊戲嗎？',
        'rules': 'Medle 遊戲規則',
        'rule-01': '猜出某段旋律中的每個音符。',
        'rule-02': '玩家不必具備音樂知識；Medle 可以是純粹的數字遊戲',
        'rule-03': '此處音符用 1 至 7 的數字表示。每次猜測後，將針對每個音符給出提示。',
        'rule-11': '音符「2」處於謎底中的正確位置。',
        'rule-12': '音符「3」出現在謎底中，但並不在猜測的位置上。',
        'rule-21': '若同一音符出現多次，則也會有對應數目的提示。',
        'rule-31': '一個音符「1」在位置正確，此外謎底還有兩個「1」，但都不在玩家猜測為1的位置上。',
        'rule-41': '遊戲中出現的其餘記號只影響發出的聲音，不影響遊戲規則。',
        'rule-51': '除數字、顏色外的記號均不影響有次。其含義留給有興趣的玩家自行探索。',
        'rule-61': '一共有 5 次机会（若謎底長度大於9個音符則為6次）。遊戲愉快！',
        'daily-update': '原版網址為 medle.0-th.art ；繁體中文用詞/翻譯問題請前去提PR；北京時間每日零時更新謎題，記得回來！',
        'guide-today-1-pfx': '正在訪問的是一份過往的謎題 ',
        'guide-today-1-sfx': '。',
        'guide-today-2-pfx': '希望繼續遊玩，還是前往今天的每日謎題 ',
        'guide-today-2-sfx': ' 呢？',
        'btn-confirm': '確認',
        'btn-share': '分享',
        'btn-shared': '已複製到剪貼簿',
        'curator': '選題',
        'curator-today': '今日選題',
        'archive': '過往謎題',
        'opt-title': '選項',
        'opt-sfx': '播放聲音',
        'opt-metronome': '節拍提示',
        'opt-dark': '深色主題',
        'opt-high-con': '清晰顯示',
        'opt-nota': '音符記號',
        'opt-nota-num': '數字',
        'opt-nota-solf': '唱名',
        'opt-nota-alpha': '字母',
        'opt-nota-roman': '羅馬',
        'opt-nota-aikin': '圖形',
        'opt-lang': '介面語言',
        'opt-source': '程序原始碼',
        'opt-dist': '依木蘭公共授權條款分發',
    }],
    ['en', 'English', {
        'loading': 'Loading…',
        'tip-1': 'Try turning on sound!',
        'tip-2': 'Press the bubbles to replay the sounds',
        'tip-3': 'Dark theme is recommended at night',
        'tip-4': 'The metronome can be brought in through the options page',
        'tip-5': 'Ever played the game with letters or shapes?',
        'rules': 'Medle Rules',
        'rule-01': 'Guess the notes in the melody.',
        'rule-02': 'No musical knowledge is required; Medle is essentially a game of numbers.',
        'rule-03': 'Notes are denoted by digits from 1 through 7. After every guess, hints will be given for each note.',
        'rule-11': 'The note “2” is in the correct place.',
        'rule-12': 'The note “3” is in the solution, but in the wrong place.',
        'rule-21': 'If a note appears more than once, more hints will be given.',
        'rule-31': 'One of the notes “1” is correct; there are additionally two such notes in the solution, but not in places guessed as “1”.',
        'rule-41': 'All other symbols affect only the sound and not the rules.',
        'rule-51': 'The game is not affected by symbols other than numbers and tints, whose meanings are left for exploration to the curious player.',
        'rule-61': 'There are 5 chances. Have fun!',
        'daily-update': 'A new puzzle is published every day at 16:00 UTC. It will be delighting to see you come back!',
        'guide-today-1-pfx': 'You are currently visiting a past puzzle ',
        'guide-today-1-sfx': '.',
        'guide-today-2-pfx': 'Would you like to continue playing, or visit today\'s daily puzzle ',
        'guide-today-2-sfx': '?',
        'btn-confirm': 'Confirm',
        'btn-share': 'Share',
        'btn-shared': 'Copied to clipboard',
        'curator': 'Curator',
        'curator-today': 'Today\'s curator',
        'archive': 'Puzzle Archive',
        'opt-title': 'Options',
        'opt-sfx': 'Play sound',
        'opt-metronome': 'Metronome',
        'opt-dark': 'Dark theme',
        'opt-high-con': 'Sharp display',
        'opt-nota': 'Notation',
        'opt-nota-num': 'Numeral',
        'opt-nota-solf': 'Solfege',
        'opt-nota-alpha': 'Alphabet',
        'opt-nota-roman': 'Roman',
        'opt-nota-aikin': 'Shape',
        'opt-lang': 'Language',
        'opt-source': 'Program source',
        'opt-dist': ' distributed under the Mulan Public License',
    }],
];